@echo off
echo Starting Ollama and pulling gemma2:2b model...
"C:\Users\sachi\AppData\Local\Programs\Ollama\ollama.exe" pull gemma2:2b
echo Model pulled! Starting Ollama server...
"C:\Users\sachi\AppData\Local\Programs\Ollama\ollama.exe" serve
