import fs from 'fs';
import path from 'path';

export function buildReport({ disease, query, answer, papers = [], trials = [], confidence }) {
  const timestamp = new Date().toISOString().split('T')[0];

  const report = `
=====================================
  CURALINK MEDICAL RESEARCH REPORT
=====================================
Date: ${timestamp}
Disease: ${disease}
Query: ${query}
Confidence: ${confidence?.score || 'N/A'}/100 (${confidence?.label || ''})
Reason: ${confidence?.reason || ''}

-------------------------------------
AI CLINICAL SUMMARY
-------------------------------------
${answer}

-------------------------------------
TOP RESEARCH PAPERS (${papers.length})
-------------------------------------
${papers.map((p, i) => `[${i + 1}] ${p.title}
    Year: ${p.year} | Source: ${p.source}
    ${p.url ? 'URL: ' + p.url : ''}`).join('\n\n')}

-------------------------------------
CLINICAL TRIALS (${trials.length})
-------------------------------------
${trials.map((t, i) => `[${i + 1}] ${t.title}
    Status: ${t.status} | Phase: ${t.phase}
    ${t.url ? 'URL: ' + t.url : ''}`).join('\n\n')}

-------------------------------------
DISCLAIMER
-------------------------------------
This report is generated by CuraLink AI for research purposes only.
It is NOT a substitute for professional medical advice.
=====================================
`;

  const filename = `curalink_report_${Date.now()}.txt`;
  const filepath = path.join(process.cwd(), 'reports', filename);

  // Ensure reports dir exists
  if (!fs.existsSync(path.join(process.cwd(), 'reports'))) {
    fs.mkdirSync(path.join(process.cwd(), 'reports'));
  }

  fs.writeFileSync(filepath, report.trim());
  return { filename, filepath, content: report.trim() };
}
